# Generated by Django 5.1.2 on 2024-10-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='cvv',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='expire',
            new_name='date_submit',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image1',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
