# Generated by Django 5.1.2 on 2024-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_rename_cvv_deposit_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
