# Generated by Django 5.1.2 on 2024-10-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0004_rooms_cur_people_rooms_sum_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtransfer",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_room",
                to="app_core.rooms",
            ),
        ),
    ]
