# Generated by Django 5.1.2 on 2024-10-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0004_rent_alter_deposit_date_submit"),
        ("app_core", "0006_remove_rooms_cur_people_remove_rooms_sum_people_and_more"),
    ]

    operations = []
